//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final___Programacion_Web_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partner()
        {
            this.partners1 = new HashSet<partner>();
        }

        [DisplayName("Id")]
        public int idPartner { get; set; }
        [DisplayName("Nombres")]
        [Required(ErrorMessage = "Proporcione el Nombre")]
        public string name { get; set; }
        [DisplayName("Apellidos")]
        [Required(ErrorMessage = "Proporcione los Apellidos")]
        public string lastname { get; set; }
        [DisplayName("Cedula")]
        [Required(ErrorMessage = "Proporcione la Cedula")]
        public string idcard { get; set; }
        [DisplayName("Foto")]
        [Required(ErrorMessage = "Proporcione el url de la foto")]
        public string photo { get; set; }
        [DisplayName("Dirección")]
        [Required(ErrorMessage = "Proporcione la Direccion")]
        public string address { get; set; }
        [DisplayName("Telefono")]
        [Required(ErrorMessage = "Proporcione el Telefono")]
        public string phone { get; set; }
        [DisplayName("Genero")]
        [Required(ErrorMessage = "Proporcione el Genero")]
        public Nullable<int> gender { get; set; }
        [DisplayName("Edad")]
        [Required(ErrorMessage = "Proporcione La Edad")]
        public int age { get; set; }
        [DisplayName("Nacimiento")]
        [Required(ErrorMessage = "Proporcione la Fecha de Nacimiento  yyyy-mm-dd")]
        public Nullable<System.DateTime> birthdate { get; set; }
        [DisplayName("Afiliado")]
        public Nullable<int> afilliate { get; set; }
        [DisplayName("Membresia")]
        [Required(ErrorMessage = "Proporcione el Tipo de Memebresia")]
        public int partnership { get; set; }
        [DisplayName("Trabajo")]
        [Required(ErrorMessage = "Proporcione el Lugar de Trabajo")]
        public string workplace { get; set; }
        [DisplayName("Dirección Of.")]
        [Required(ErrorMessage = "Proporcione la Direccion de la Oficina")]
        public string officeaddress { get; set; }
        [DisplayName("Telefono Of.")]
        [Required(ErrorMessage = "Proporcione el Telefono de la Oficina")]
        public string officephone { get; set; }
        [DisplayName("Activo")]
        [Required(ErrorMessage = "Proporcione si esta activo(1) o inactivo(0)")]
        public int partnershipstatus { get; set; }
        [DisplayName("Admisión")]
        [Required(ErrorMessage = "Proporcione la Fecha de Admision yyyy-mm-dd")]
        public Nullable<System.DateTime> addmisiondate { get; set; }
        [DisplayName("Salida")]
        public Nullable<System.DateTime> departuredate { get; set; }
    
        public virtual gender gender1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner> partners1 { get; set; }
        public virtual partner partner1 { get; set; }
        public virtual partnership partnership1 { get; set; }
    }
}
