//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final___Programacion_Web_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user
    {

        public int idUser { get; set; }

        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Proporcione el Email")]
        public string email { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Proporcione Password")]
        public string password { get; set; }

        [DisplayName("Cornfirmar Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Repita el Password")]
        [Compare("password")]
        public string confirmPassword { get; set; }
    }
}
